// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErrorHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidErrorHelperPackageString = "3f9fa707-35b8-42f5-a623-8fa0ab37a05c";
        public static Guid guidErrorHelperPackage = new Guid(guidErrorHelperPackageString);

        public const string guidErrorHelperPackageCmdSetString = "5fea58eb-df34-46e8-ab5d-4708b07cf330";
        public static Guid guidErrorHelperPackageCmdSet = new Guid(guidErrorHelperPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CopyDescriptionCommandId = 0x0100;
        public const int cmdidSearchDescriptionCommand = 0x1021;
    }
}