// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErrorHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "ErrorHelper.e90a7159-7bf3-45f6-b3d5-e80fd5978133";
        public const string Name = "Error Helper";
        public const string Description = @"Helper for using the ErrorList Description.";
        public const string Language = "en-US";
        public const string Version = "2.8.5";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
